version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data
    restart: unless-stopped
    networks:
      - app-network

  backend:
    image: enurovi/wezoo:backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rust-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres?currentSchema=public
      SECRET: 8zvAZrDR3RLN7z7v5rJu4Ie71i929ftK
      ADDRESS: backend
      PORT: 8080
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: enurovi/wezoo:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
