//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "marking")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub report_id: i32,
    pub mark: String,
    #[sea_orm(unique)]
    pub goods_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::goods::Entity",
        from = "Column::GoodsId",
        to = "super::goods::Column::IdExt",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Goods,
    #[sea_orm(
        belongs_to = "super::reports::Entity",
        from = "Column::ReportId",
        to = "super::reports::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Reports,
}

impl Related<super::goods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Goods.def()
    }
}

impl Related<super::reports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
