//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pet_breeds")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub pet_types_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pet_types::Entity",
        from = "Column::PetTypesId",
        to = "super::pet_types::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    PetTypes,
    #[sea_orm(has_many = "super::pets::Entity")]
    Pets,
}

impl Related<super::pet_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PetTypes.def()
    }
}

impl Related<super::pets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
