//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pet_types")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::goods_pets::Entity")]
    GoodsPets,
    #[sea_orm(has_many = "super::pet_breeds::Entity")]
    PetBreeds,
    #[sea_orm(has_many = "super::pets::Entity")]
    Pets,
}

impl Related<super::goods_pets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GoodsPets.def()
    }
}

impl Related<super::pet_breeds::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PetBreeds.def()
    }
}

impl Related<super::pets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
