//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::cliniks::Entity as Cliniks;
pub use super::goods::Entity as Goods;
pub use super::goods_classes::Entity as GoodsClasses;
pub use super::goods_group::Entity as GoodsGroup;
pub use super::goods_orgs::Entity as GoodsOrgs;
pub use super::goods_pets::Entity as GoodsPets;
pub use super::marking::Entity as Marking;
pub use super::orders::Entity as Orders;
pub use super::organizations::Entity as Organizations;
pub use super::pet_breeds::Entity as PetBreeds;
pub use super::pet_types::Entity as PetTypes;
pub use super::pets::Entity as Pets;
pub use super::producers::Entity as Producers;
pub use super::reports::Entity as Reports;
pub use super::stocks::Entity as Stocks;
pub use super::user::Entity as User;
