//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stocks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub goods_id: String,
    pub clinic_id: i32,
    pub quantity: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cliniks::Entity",
        from = "Column::ClinicId",
        to = "super::cliniks::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Cliniks,
    #[sea_orm(
        belongs_to = "super::goods::Entity",
        from = "Column::GoodsId",
        to = "super::goods::Column::IdExt",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Goods,
}

impl Related<super::cliniks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cliniks.def()
    }
}

impl Related<super::goods::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Goods.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
